const $ = s => document.querySelector(s);
const colors = [
  ['Primary','#7C3AED','124, 58, 237','--primary'],['Background','#050505','5, 5, 5','--background'],['Text','#F5F3FA','245, 243, 250','--text'],['Accent','#45A3FF','69, 163, 255','--accent'],['Surface','#17151E','23, 21, 30','--surface'],['Muted','#94919E','148, 145, 158','--muted']
];
const cssText = `:root {\n  --background: #050505;\n  --surface: #17151E;\n  --primary: #7C3AED;\n  --accent: #45A3FF;\n  --text: #F5F3FA;\n  --radius: 24px;\n  --shadow: 0 20px 40px rgba(0, 0, 0, .28);\n  --blur: 20px;\n}`;
const demoImage = `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="920" height="650" viewBox="0 0 920 650"><defs><linearGradient id="a" x1="0" x2="1"><stop stop-color="#6440e7"/><stop offset="1" stop-color="#3687dc"/></linearGradient><radialGradient id="b"><stop stop-color="#4927a9"/><stop offset="1" stop-color="#101015"/></radialGradient></defs><rect width="920" height="650" fill="#101015"/><rect x="0" width="920" height="62" fill="#15151c"/><circle cx="45" cy="31" r="11" fill="url(#a)"/><text x="65" y="38" fill="white" font-size="18" font-family="Arial" font-weight="bold">nexora</text><text x="605" y="37" fill="#bcbac8" font-size="13" font-family="Arial">Product   Solutions   Resources   Pricing</text><rect x="770" y="16" width="102" height="31" rx="8" fill="url(#a)"/><text x="794" y="37" fill="white" font-size="12" font-family="Arial">Get started</text><rect y="62" width="920" height="465" fill="url(#b)"/><text x="70" y="195" fill="#aaa5c7" font-size="13" font-family="Arial">THE OPERATING SYSTEM FOR TEAMS</text><text x="67" y="260" fill="white" font-size="58" font-family="Arial" font-weight="bold">Work at the speed</text><text x="67" y="323" fill="white" font-size="58" font-family="Arial" font-weight="bold">of <tspan fill="#a583ff">your ideas.</tspan></text><text x="70" y="370" fill="#aaa8b4" font-size="17" font-family="Arial">One calm, connected workspace for the teams</text><text x="70" y="396" fill="#aaa8b4" font-size="17" font-family="Arial">building what's next.</text><rect x="70" y="430" width="130" height="45" rx="10" fill="url(#a)"/><text x="91" y="458" fill="white" font-size="14" font-family="Arial">Start building →</text><rect x="525" y="145" width="295" height="300" rx="16" fill="#1e1c29" stroke="#4f4867"/><rect x="548" y="170" width="250" height="30" rx="6" fill="#292637"/><circle cx="566" cy="185" r="6" fill="#926eff"/><rect x="580" y="179" width="88" height="10" rx="3" fill="#ded9eb"/><rect x="550" y="223" width="105" height="83" rx="10" fill="#292637"/><rect x="667" y="223" width="130" height="83" rx="10" fill="#292637"/><rect x="550" y="318" width="248" height="100" rx="10" fill="#292637"/><path d="M570 391 C620 330 650 400 695 355 S750 370 780 335" stroke="#7956eb" stroke-width="4" fill="none"/><rect y="527" width="920" height="123" fill="#15151c"/><text x="70" y="580" fill="#8f8b9c" font-size="12" font-family="Arial">TRUSTED BY TEAMS AT</text><text x="70" y="621" fill="white" font-size="20" font-family="Arial">Vercel     Linear     Framer     Raycast</text></svg>`)}`;
function renderColors(){ $('#colorGrid').innerHTML=colors.map(([name,hex,rgb,variable])=>`<div class="color-card"><div class="swatch" style="background:${hex}"></div><div><b>${name}</b><small>${hex} · rgb(${rgb})</small></div><button class="copy-value" data-value="${variable}: ${hex};" title="Скопировать">⧉</button></div>`).join(''); }
function toast(msg='Скопировано в буфер обмена'){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function copy(value){try{await navigator.clipboard.writeText(value);toast()}catch{toast('Не удалось скопировать')}}
function showWorkspace(src){ $('#screenshot').src=src; $('#hero').classList.add('hidden');$('#dropSection').classList.add('hidden');$('#workspace').classList.remove('hidden');localStorage.setItem('copyThatLastImage',src);setTimeout(()=>$('#workspace').scrollIntoView({behavior:'smooth'}),50);}
function startAnalysis(src){$('#loader').classList.remove('hidden'); const texts=['Анализируем интерфейс...','Анализируем цвета...','Строим структуру...','Готово.']; let i=0;const timer=setInterval(()=>{i++;if(i<texts.length)$('#loaderText').textContent=texts[i]},520);setTimeout(()=>{clearInterval(timer);$('#loader').classList.add('hidden');showWorkspace(src)},2100)}
function fileUpload(file){if(!file || !file.type.startsWith('image/'))return toast('Выберите изображение PNG, JPG или WEBP');if(file.size>10*1024*1024)return toast('Файл больше 10 МБ');const reader=new FileReader();reader.onload=e=>startAnalysis(e.target.result);reader.readAsDataURL(file)}
function download(filename,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
renderColors();$('#cssCode').textContent=cssText;
document.querySelectorAll('[data-upload]').forEach(b=>b.addEventListener('click',()=>$('#fileInput').click()));
$('#fileInput').addEventListener('change',e=>fileUpload(e.target.files[0]));
const zone=$('#dropZone');['dragenter','dragover'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>fileUpload(e.dataTransfer.files[0]));
$('#demoBtn').addEventListener('click',()=>startAnalysis(demoImage));
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button,.tab-content').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')}));
document.addEventListener('click',e=>{const btn=e.target.closest('.copy-value,.copy-code');if(btn)copy(btn.dataset.value||btn.dataset.code)});
$('#copyPalette').addEventListener('click',()=>copy(colors.map(c=>`${c[3]}: ${c[1]};`).join('\n')));$('#copyCss').addEventListener('click',()=>copy(cssText));$('#downloadCss').addEventListener('click',()=>download('copy-that-ui-tokens.css',cssText,'text/css'));$('#downloadJson').addEventListener('click',()=>download('copy-that-ui-analysis.json',JSON.stringify({project:'Copy That UI',colors:Object.fromEntries(colors.map(c=>[c[0],c[1]])),styles:{radius:'24px',blur:'20px',spacing:'8px system'},components:['Primary button','Navigation bar','Glass card','Hero block']},null,2),'application/json'));
$('#gridToggle').addEventListener('click',e=>{e.currentTarget.classList.toggle('active');$('.grid-overlay').style.display=e.currentTarget.classList.contains('active')?'block':'none'});$('#blocksToggle').addEventListener('click',e=>{e.currentTarget.classList.toggle('active');$('.blocks-overlay').style.display=e.currentTarget.classList.contains('active')?'block':'none'});$('#compareToggle').addEventListener('click',e=>{e.currentTarget.classList.toggle('active');$('#canvasWrap').classList.toggle('compare');toast('Режим сравнения: оригинал слева, стиль справа')});
$('#canvasWrap').addEventListener('click',e=>{const img=$('#screenshot');if(!img.complete)return;const r=img.getBoundingClientRect(),x=Math.round((e.clientX-r.left)*img.naturalWidth/r.width),y=Math.round((e.clientY-r.top)*img.naturalHeight/r.height);const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);try{const d=ctx.getImageData(x,y,1,1).data,hex='#'+[d[0],d[1],d[2]].map(n=>n.toString(16).padStart(2,'0')).join('').toUpperCase();$('#pickedColor span').style.background=hex;$('#pickedColor p').textContent='Цвет на выбранной точке';$('#pickedColor code').textContent=hex;const dot=$('#pickerDot');dot.style.display='block';dot.style.left=(e.clientX-r.left)+'px';dot.style.top=(e.clientY-r.top)+'px'}catch{toast('Невозможно взять цвет с этого изображения')}});
$('#resetBtn').addEventListener('click',()=>{localStorage.removeItem('copyThatLastImage');$('#workspace').classList.add('hidden');$('#hero').classList.remove('hidden');$('#dropSection').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})});
const saved=localStorage.getItem('copyThatLastImage');if(saved){$('#screenshot').src=saved;}
