import { assertPublicUrl } from "@/lib/ssrf";
import type { AnalysisReport, Categories, Finding } from "@/types/analysis";
const MAX_BYTES=900_000, TIMEOUT=12_000, UA="SITECHECK/1.0 (+website audit; passive analysis)";
const attr=(tag:string,name:string)=>new RegExp(`${name}\\s*=\\s*["']([^"']*)["']`,"i").exec(tag)?.[1]??null;
const text=(html:string,pattern:RegExp)=>pattern.exec(html)?.[1].replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()??null;
const finding=(status:Finding["status"],priority:Finding["priority"],title:string,description:string,recommendation:string,category:Finding["category"]):Finding=>({id:crypto.randomUUID(),status,priority,title,description,recommendation,category});
async function safeFetch(url:string){let target=url; for(let redirects=0;redirects<4;redirects++){await assertPublicUrl(target); const controller=new AbortController(), timeout=setTimeout(()=>controller.abort(),TIMEOUT),start=performance.now(); try { const response=await fetch(target,{redirect:"manual",signal:controller.signal,headers:{"user-agent":UA,"accept":"text/html,application/xhtml+xml"}}); clearTimeout(timeout); if([301,302,303,307,308].includes(response.status)){const location=response.headers.get("location");if(!location)throw new Error("Сайт вернул некорректное перенаправление.");target=new URL(location,target).toString();continue} if(!response.ok) throw new Error(response.status===403?"Сайт запретил доступ для проверки (403).":`Сайт вернул ошибку ${response.status}.`); const reader=response.body?.getReader();if(!reader)throw new Error("Сайт не вернул содержимое страницы.");let size=0,chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>MAX_BYTES){await reader.cancel();throw new Error("Главная страница слишком большая для базовой проверки.")}chunks.push(value)} return {url:target,html:new TextDecoder().decode(Buffer.concat(chunks)),headers:response.headers,status:response.status,time:Math.round(performance.now()-start)}; } catch(e){clearTimeout(timeout);if(e instanceof Error&&e.name==="AbortError")throw new Error("Сайт отвечает слишком долго. Попробуйте позже.");throw e;} } throw new Error("Слишком много перенаправлений.");}
const score=(base:number, bad:number)=>Math.max(0,Math.min(100,base-bad));
export async function analyzeSite(url:string):Promise<AnalysisReport>{const data=await safeFetch(url),html=data.html,lower=html.toLowerCase(),issues:Finding[]=[],positives:Finding[]=[];const add=(f:Finding)=>f.status==="pass"?positives.push(f):issues.push(f);
const title=text(html,/<title[^>]*>([\s\S]*?)<\/title>/i),description=(/<meta\b[^>]*name\s*=\s*["']description["'][^>]*>/i.exec(html)||/<meta\b[^>]*content\s*=\s*["'][^"']*["'][^>]*name\s*=\s*["']description["'][^>]*>/i.exec(html))?.[0],desc=description?attr(description,"content"):null; const h1=(html.match(/<h1\b[^>]*>/gi)||[]).length,h2=(html.match(/<h2\b[^>]*>/gi)||[]).length,lang=attr(/<html\b[^>]*>/i.exec(html)?.[0]||"","lang"),viewport=/<meta\b[^>]*name\s*=\s*["']viewport["']/i.test(html),canonical=/<link\b[^>]*rel\s*=\s*["']canonical["']/i.test(html),og=/<meta\b[^>]*property\s*=\s*["']og:/i.test(html),favicon=/<link\b[^>]*rel\s*=\s*["'][^"']*icon/i.test(html);
add(title?finding("pass","low","Title присутствует",`Найден title длиной ${title.length} символов.`,``, "seo"):finding("error","high","Не найден Title","У страницы нет тега title.","Добавьте уникальный title длиной около 30–60 символов.","seo"));if(title&&(title.length<25||title.length>65))add(finding("warning","medium","Неоптимальная длина Title",`Длина title: ${title.length} символов.`,`Сделайте title более информативным, ориентир — 30–60 символов.`,"seo"));
add(desc?finding("pass","low","Meta Description присутствует",`Найдено описание длиной ${desc.length} символов.`,``,"seo"):finding("error","high","Meta Description отсутствует","Поисковая система будет сама формировать сниппет страницы.","Добавьте уникальное description длиной примерно 120–160 символов.","seo"));add(h1===1?finding("pass","low","Один H1 на странице","Главный заголовок страницы определён.","","seo"):finding("warning",h1===0?"high":"medium",h1===0?"H1 отсутствует":"Несколько H1 на странице",`Найдено H1: ${h1}.`,`Используйте один ясный H1, описывающий основное содержание страницы.`,"seo"));
add(lang?finding("pass","low","Язык документа указан",`Найден lang=\"${lang}\".`,``,"accessibility"):finding("warning","medium","Язык страницы не указан","У тега html нет атрибута lang.","Добавьте lang к тегу html, например lang=\"ru\".","accessibility"));add(viewport?finding("pass","low","Viewport настроен","Страница заявляет адаптацию для мобильных устройств.","","mobile"):finding("error","high","Не настроен viewport","Мобильные браузеры могут отображать страницу в неверном масштабе.","Добавьте meta viewport с width=device-width, initial-scale=1.","mobile"));
const imgs=[...html.matchAll(/<img\b[^>]*>/gi)].map(x=>x[0]),withoutAlt=imgs.filter(x=>!(/\balt\s*=/.test(x))).length,lazy=imgs.filter(x=>/loading\s*=\s*["']lazy/i.test(x)).length;if(imgs.length)add(withoutAlt?finding("warning","medium","У изображений нет alt",`${withoutAlt} из ${imgs.length} изображений не имеют альтернативного текста.`,`Добавьте осмысленный alt к содержательным изображениям.`,"accessibility"):finding("pass","low","Изображения имеют alt",`Проверено изображений: ${imgs.length}.`,"","accessibility"));if(imgs.length>5&&lazy===0)add(finding("warning","low","Изображения не используют lazy loading",`На странице ${imgs.length} изображений, loading=\"lazy\" не найден.`,`Добавьте lazy loading для изображений ниже первого экрана.`,"performance"));
add(lower.startsWith("<!doctype html")?finding("pass","low","DOCTYPE присутствует","Документ использует современный doctype.","","technical"):finding("warning","medium","DOCTYPE не найден","Браузер может включить режим совместимости.","Начинайте HTML-документ с <!doctype html>.","technical"));if(!data.url.startsWith("https:"))add(finding("error","critical","Сайт работает без HTTPS","Передача данных по HTTP небезопасна.","Настройте HTTPS и редирект с HTTP на HTTPS.","technical")); else add(finding("pass","low","HTTPS включён","Страница загружена по защищённому соединению.","","technical"));
for(const [header,label] of [["content-security-policy","Content-Security-Policy"],["x-content-type-options","X-Content-Type-Options"],["referrer-policy","Referrer-Policy"],["strict-transport-security","HSTS"]] as const)if(!data.headers.get(header))add(finding("warning","low",`Не найден заголовок ${label}`,"Базовый заголовок безопасности отсутствует в ответе.",`Настройте ${label} на веб-сервере.`,"technical"));
if(!canonical)add(finding("warning","low","Canonical не указан","Поисковикам сложнее определить основной URL страницы.","Добавьте canonical URL в head страницы.","seo"));if(!og)add(finding("warning","low","Open Graph не найден","Ссылка может выглядеть менее информативно в социальных сетях.","Добавьте основные Open Graph метатеги.","seo"));if(!favicon)add(finding("warning","low","Favicon не найден","Браузер не обнаружил стандартную ссылку на favicon.","Добавьте link rel=\"icon\" в head страницы.","seo"));
const forms=(html.match(/<form\b/gi)||[]).length,links=(html.match(/<a\b/gi)||[]).length,scripts=(html.match(/<script\b/gi)||[]).length,styles=(html.match(/<link\b[^>]*stylesheet/gi)||[]).length;const categories:Categories={seo:score(100,issues.filter(x=>x.category==="seo").reduce((a,x)=>a+({critical:35,high:22,medium:12,low:5}[x.priority]),0)),performance:score(100,(data.time>1200?22:data.time>600?10:0)+(imgs.length>18?12:0)+(scripts>12?8:0)+(styles>8?6:0)),mobile:score(100,issues.filter(x=>x.category==="mobile").reduce((a,x)=>a+({critical:35,high:22,medium:12,low:5}[x.priority]),0)),accessibility:score(100,issues.filter(x=>x.category==="accessibility").reduce((a,x)=>a+({critical:35,high:22,medium:12,low:5}[x.priority]),0)),technical:score(100,issues.filter(x=>x.category==="technical").reduce((a,x)=>a+({critical:35,high:22,medium:12,low:5}[x.priority]),0))};const total=Math.round(categories.performance*.25+categories.seo*.25+categories.mobile*.2+categories.accessibility*.15+categories.technical*.15);return {id:crypto.randomUUID(),url:data.url,createdAt:new Date().toISOString(),score:total,categories,issues,positives,meta:{title,description:desc,lang},stats:{status:data.status,responseTime:data.time,htmlSize:Buffer.byteLength(html),images:imgs.length,links,forms}};}
